spring:
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb+srv://Emanuel:79708797ea65514444ea@web-development.khfadhl.mongodb.net/capstone_db?retryWrites=true&w=majority&authSource=admin}

  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      indent-output: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

server:
  port: 8080
  servlet:
    context-path: /

supabase:
  jwt:
    secret: ${SUPABASE_JWT_SECRET:qN1rsGf6PyPsS7qAtXbL6fPAtwjIyDydBfp/dNwTFqmtWlewvcuuEBZd4ObEGDeOQ17jjE9dJeqeSrYYSZoWVA==}